export default {
  SET_FILTER_CATEGORY: "SET_FILTER_CATEGORY",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_REVIEWS: "SET_REVIEWS",
  SET_PRODUCT: "SET_PRODUCT",
  SET_ERROR: "SET_ERROR",
  IS_LOADING: "IS_LOADING",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
};
