export default {
  SET_CART: "SET_CART",
  EMPTY_CART: "EMPTY_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  TRIGGER_CART: "TRIGGER_CART",
};
